import test from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';
import {FIELD,emptyData,event,mirrorGame,isBreak,pullMetrics,statsFor,gameState,mergeData,validateData,playersForGroup,lineSlots,teamRates} from '../web/core.js';import {readStattoZip,convertStatto} from '../web/statto.js';
const team={id:'t',name:'Team',players:Array.from({length:7},(_,i)=>({id:'p'+i,name:'Player '+i,number:String(i)}))};
const make=()=>({id:'g',teamId:'t',opponent:'Other',opponents:[],field:FIELD,events:[]});
const start=(g,starting='O',direction=1)=>g.events.push(event('point_start',{line:team.players.map(p=>p.id),starting,direction}));
const pickup=(g,side,playerId,location={x:25,y:20})=>g.events.push(event('possession_start',{side,playerId,location}));
const pass=(g,props)=>g.events.push(event('pass',{side:'us',throwerId:'p0',receiverId:'p1',from:{x:25,y:20},to:{x:28,y:24},outcome:'complete',...props}));
const stats=g=>Object.fromEntries(statsFor([team],[g]).map(p=>[p.id,p]));
test('completed yardage, backward gain, goal and secondary assist are derived',()=>{const g=make();start(g);pickup(g,'us','p0');pass(g,{});pass(g,{throwerId:'p1',receiverId:'p2',from:{x:28,y:24},to:{x:24,y:24}});pass(g,{throwerId:'p2',receiverId:'p3',from:{x:24,y:24},to:{x:92,y:24},outcome:'goal'});const s=stats(g);assert.equal(s.p0.throwDistance,5);assert.equal(s.p0.throwGain,3);assert.equal(s.p1.catchDistance,5);assert.equal(s.p1.throwGain,-4);assert.equal(s.p1.secondaryAssists,1);assert.equal(s.p0.secondaryAssists,0);assert.equal(s.p2.assists,1);assert.equal(s.p3.goals,1);assert.equal(s.p0.initiated,1);assert.deepEqual(gameState(g).score,[1,0]);assert.equal(gameState(g).nextStarting,'D');assert.equal(s.p6.opportunities,1);});
test('opponent receiver defender becomes next marker; defense metrics',()=>{const g=make();start(g,'D');pickup(g,'them',null);pass(g,{side:'them',throwerId:null,receiverId:'opp1',markerId:'p0',receiverDefenderId:'p1'});let state=gameState(g);assert.equal(state.marker,'p1');assert.equal(state.holder,'opp1');pass(g,{side:'them',throwerId:'opp1',receiverId:null,from:{x:28,y:24},to:{x:18,y:24},markerId:state.marker,receiverDefenderId:'p2',outcome:'goal'});const s=stats(g);assert.equal(s.p0.throwAllowed,5);assert.equal(s.p1.receiveAllowed,5);assert.equal(s.p1.throwAllowed,10);assert.equal(s.p1.assistsAllowed,1);assert.equal(s.p2.goalsAllowed,1);assert.equal(s.p2.targets,1);assert.equal(s.p6.opportunities,0);assert.equal(gameState(g).nextStarting,'O');});
test('turnovers award defensive opportunity once and exclude incomplete yardage',()=>{const g=make();start(g,'D');pickup(g,'them',null);pass(g,{side:'them',markerId:'p4',receiverDefenderId:'p3',outcome:'throwaway'});assert.equal(gameState(g).needsPickup,true);assert.equal(gameState(g).side,'us');pickup(g,'us','p2');pass(g,{throwerId:'p2',receiverId:'p1',outcome:'drop'});pickup(g,'them',null);pass(g,{side:'them',markerId:'p0',receiverDefenderId:'p1',blockerId:'p5',outcome:'block'});const s=stats(g);assert.equal(s.p4.forcedThrowaways,1);assert.equal(s.p3.targets,1);assert.equal(s.p4.throwAllowed,0);assert.equal(s.p2.throwDistance,0);assert.equal(s.p1.drops,1);assert.equal(s.p2.throwaways,0);assert.equal(s.p5.blocks,1);assert.equal(s.p6.opportunities,1);});
test('reverse direction produces positive forward gain and undo recalculates score',()=>{const g=make();start(g,'O',-1);pickup(g,'us','p0');pass(g,{from:{x:35,y:20},to:{x:15,y:20},outcome:'goal'});assert.equal(stats(g).p0.throwGain,20);g.events.pop();assert.equal(stats(g).p1.goals,0);assert.deepEqual(gameState(g).score,[0,0]);assert.equal(gameState(g).active,true);});
test('a turnover breaks the secondary assist chain',()=>{const g=make();start(g);pickup(g,'us','p0');pass(g,{});pass(g,{throwerId:'p1',outcome:'throwaway'});pickup(g,'us','p2');pass(g,{throwerId:'p2',receiverId:'p3',outcome:'goal'});assert.equal(stats(g).p0.secondaryAssists,0);});
test('rate summary derives holds, breaks, turnovers, and hucks from play-by-play',()=>{const g=make();start(g,'O');pickup(g,'us','p0',{x:20,y:20});pass(g,{from:{x:20,y:20},to:{x:60,y:20},outcome:'complete'});g.events.push(event('point_end',{winner:'us'}));start(g,'O');pickup(g,'us','p0');pass(g,{outcome:'throwaway'});g.events.push(event('point_end',{winner:'them'}));start(g,'D');pickup(g,'them',null);pass(g,{side:'them',outcome:'throwaway'});pickup(g,'us','p0');pass(g,{outcome:'goal'});g.events.push(event('point_end',{winner:'us'}));const r=teamRates([g],35);assert.deepEqual(r,{offense:2,holds:1,cleanHolds:1,defense:1,turns:1,breaks:1,huckAttempts:1,huckCompletions:1});});
test('player huck completion rate follows the configured distance threshold',()=>{const g=make();start(g);pickup(g,'us','p0',{x:10,y:20});pass(g,{from:{x:10,y:20},to:{x:50,y:20},outcome:'complete'});pass(g,{throwerId:'p1',from:{x:50,y:20},to:{x:90,y:20},outcome:'throwaway'});let s=stats(g);assert.equal(s.p0.huckCompletionRate,1);assert.equal(s.p1.huckCompletionRate,0);s=Object.fromEntries(statsFor([team],[g],45).map(player=>[player.id,player]));assert.equal(s.p0.huckAttempts,0);assert.equal(s.p1.huckAttempts,0);});
test('JSON round trip and idempotent game merge',()=>{const g=make();start(g);const d={...emptyData(),teams:[team],games:[g]};validateData(d);const round=JSON.parse(JSON.stringify(d));assert.deepEqual(statsFor(d.teams,d.games),statsFor(round.teams,round.games));const a=mergeData(emptyData(),round);const b=mergeData(a.data,round);assert.equal(a.added,1);assert.equal(b.added,0);assert.equal(b.skipped,1);assert.equal(b.data.teams[0].players.length,7);});
test('invalid imports are rejected',()=>{assert.throws(()=>validateData({format:'righttrousers',version:4}));const g=make();start(g);pass(g,{to:{x:NaN,y:1}});assert.throws(()=>validateData({...emptyData(),teams:[team],games:[g]}),/coordinates/);});
test('player groups filter the roster without changing roster order',()=>{const grouped={...team,groups:[{id:'o-line',name:'O-line',playerIds:['p4','p1','p6']}]};assert.deepEqual(playersForGroup(grouped,'o-line').map(player=>player.id),['p1','p4','p6']);assert.equal(playersForGroup(grouped,'all').length,7);assert.deepEqual(playersForGroup(grouped,'missing'),[]);validateData({...emptyData(),teams:[grouped]});});
test('short lines are padded with Unknown slots and capped at seven',()=>{const slots=lineSlots(team.players,['p0','p2']);assert.equal(slots.length,7);assert.deepEqual(slots.slice(0,2).map(player=>player.id),['p0','p2']);assert.equal(slots.filter(player=>player===null).length,5);assert.equal(lineSlots(team.players,team.players.map(player=>player.id).concat('extra')).length,7);const g=make();g.events.push(event('point_start',{line:['p0'],opponentLine:['opp'],starting:'O',direction:1}));validateData({...emptyData(),teams:[team],games:[g]});});
test('substitutions update the active line and credit everyone who appeared',()=>{const expanded={...team,players:[...team.players,{id:'p7',name:'Player 7',number:'7'}]},g=make();start(g);g.events.push(event('substitution',{side:'us',outId:'p6',inId:'p7'}));const s=Object.fromEntries(statsFor([expanded],[g]).map(player=>[player.id,player]));assert.equal(gameState(g).point.line.includes('p6'),false);assert.equal(gameState(g).point.line.includes('p7'),true);assert.equal(s.p6.points,1);assert.equal(s.p7.points,1);validateData({...emptyData(),teams:[expanded],games:[g]});});
test('a substitution can fill an open line slot',()=>{const expanded={...team,players:[...team.players,{id:'p7',name:'Player 7',number:'7'}]},g=make();g.events.push(event('point_start',{line:['p0'],starting:'O',direction:1}));g.events.push(event('substitution',{side:'us',outId:null,inId:'p7'}));assert.deepEqual(gameState(g).point.line,['p0','p7']);validateData({...emptyData(),teams:[expanded],games:[g]});});
test('group imports merge once and reject missing player references',()=>{const grouped={...team,groups:[{id:'o-line',name:'O-line',playerIds:['p0']}]},incoming={...emptyData(),teams:[grouped]};const first=mergeData({...emptyData(),teams:[{...team,groups:[]}]},incoming),second=mergeData(first.data,incoming);assert.equal(first.data.teams[0].groups.length,1);assert.equal(second.data.teams[0].groups.length,1);assert.throws(()=>validateData({...emptyData(),teams:[{...grouped,groups:[{id:'bad',name:'Bad',playerIds:['absent']}]}]}),/missing player/);});
test('Statto converter rotates coordinates, preserves raw source, and derives score',()=>{const raw={filename:'sample',teams:[{data:{team:{uuid:'t',name:'Team'},relations:{players:team.players.map(p=>({uuid:p.id,name:p.name,number:Number(p.number)})),games:[{uuid:'g',opponent:'Other',isFinished:true,pitchKind:0}],points:[{uuid:'pt',gameUUID:'g',isOffense:true,result:1,playerUUIDs:team.players.map(p=>p.id)}],possessions:[{uuid:'pos',pointUUID:'pt',initiatorUUID:'p0',startX:.5,startY:.8,createdAt:'2025-01-01T00:00:01Z'}],passes:[{uuid:'pass',possessionUUID:'pos',throwerUUID:'p0',receiverUUID:'p1',startX:.5,startY:.8,endX:.5,endY:.1,isAssist:true,createdAt:'2025-01-01T00:00:02Z'}]}}}]};const d=convertStatto(raw);const p=d.games[0].events.find(e=>e.type==='pass');assert.equal(p.to.x,99);assert.equal(p.to.y,20);assert.deepEqual(gameState(d.games[0]).score,[1,0]);assert.equal(statsFor(d.teams,d.games).find(p=>p.id==='p1').goals,1);assert.equal(d.sources[0].original,raw);});
const sample=process.env.STATTO_SAMPLE;
test('real Statto archive: all passes and points survive, raw metadata retained',{skip:!sample},async()=>{const b=await readFile(sample);const raw=await readStattoZip(b.buffer.slice(b.byteOffset,b.byteOffset+b.byteLength));const d=convertStatto(raw);assert.equal(d.teams.length,6);assert.equal(d.games.length,29);assert.equal(d.games.reduce((n,g)=>n+g.events.filter(e=>e.type==='pass').length,0),4113);assert.equal(d.games.reduce((n,g)=>n+g.events.filter(e=>e.type==='point_start').length,0),641);for(const t of raw.teams)for(const g of t.data.relations.games){const converted=d.games.find(x=>x.id===g.uuid),points=t.data.relations.points.filter(p=>p.gameUUID===g.uuid);assert.deepEqual(gameState(converted).score,[points.filter(p=>p.result===1).length,points.filter(p=>p.result===-1).length]);}assert.equal(d.sources[0].original.metadata.appVersion,'1.7.0');assert.deepEqual(statsFor(d.teams,d.games),statsFor(d.teams,JSON.parse(JSON.stringify(d.games))));});
test('our offense tracks the opponent defender chain after a turnover',()=>{const g=make();start(g,'D');g.events.push(event('possession_start',{side:'us',playerId:'p0',location:{x:25,y:20},opponentMarkerId:'opp0'}));assert.equal(gameState(g).marker,'opp0');pass(g,{opponentReceiverDefenderId:'opp1'});assert.equal(gameState(g).marker,'opp1');});
test('mirrored game gives the opponent a first-person view',()=>{const g=make();g.opponents=[{id:'opp0',name:'Opp 0',number:'0'}];g.events.push(event('point_start',{line:['p0'],opponentLine:['opp0'],starting:'D',direction:1}));g.events.push(event('possession_start',{side:'them',playerId:'opp0',location:{x:25,y:20}}));g.events.push(event('pass',{side:'them',throwerId:'opp0',receiverId:null,from:{x:25,y:20},to:{x:25,y:20},outcome:'throwaway',markerId:'p0',receiverDefenderId:null}));const opponentTeam={id:'o',name:'Other',players:g.opponents},rows=Object.fromEntries(statsFor([opponentTeam],[mirrorGame(g)]).map(r=>[r.id,r]));assert.equal(rows.opp0.oPoints,1);assert.equal(rows.opp0.initiated,1);assert.equal(rows.opp0.throwaways,1);assert.equal(statsFor([team],[mirrorGame(g)]).find(r=>r.id==='p0').dPoints,0);});
test('break detection follows the force from the thrower facing their attacking end zone',()=>{const point={direction:1},throwTo=(side,force,dx,dy,fromY=20)=>isBreak({side,force,from:{x:50,y:fromY},to:{x:50+dx,y:fromY+dy}},point,FIELD);
 // attacking +x on screen, the thrower's right (forehand side) is +y
 assert.equal(throwTo('us','forehand',5,-6),true);assert.equal(throwTo('us','forehand',5,6),false);assert.equal(throwTo('us','forehand',5,-4),false);assert.equal(throwTo('us','forehand',-1,-10),false);assert.equal(throwTo('us','forehand',0,-10),true);
 assert.equal(throwTo('us','backhand',5,6),true);assert.equal(throwTo('us','backhand',5,-6),false);
 // opponent attacks -x, so their right is -y
 assert.equal(throwTo('them','forehand',-5,6),true);assert.equal(throwTo('them','forehand',-5,-6),false);
 // middle: thrower near y=5 is forced toward +y, so breaking goes toward the near sideline
 assert.equal(throwTo('us','middle',5,-4.5,5),false);assert.equal(throwTo('us','middle',5,-5.5,10),true);assert.equal(throwTo('us','middle',5,10,10),false);assert.equal(throwTo('us','middle',5,-6,30),false);assert.equal(throwTo('us','middle',5,6,30),true);
 assert.equal(isBreak({side:'us',force:null,from:{x:50,y:20},to:{x:60,y:5}},point,FIELD),false);});
test('breaks credit the thrower and charge the marker',()=>{const g=make();start(g);pickup(g,'us','p0');pass(g,{force:'forehand',break:true});pickup(g,'them',null);pass(g,{side:'them',throwerId:null,receiverId:null,markerId:'p3',force:'backhand',break:true});const s=stats(g);assert.equal(s.p0.breaks,1);assert.equal(s.p3.breaksAllowed,1);assert.equal(s.p1.breaks,0);});
test('pull distances run from the pulling goal line and the brick marks an out-of-bounds pull',()=>{const g=make();g.events.push(event('point_start',{line:team.players.map(p=>p.id),starting:'D',direction:1}));g.events.push(event('possession_start',{side:'them',playerId:null,pullerId:'p0',location:{x:70,y:30}}));
 // we pull attacking +x from x=20, so a pickup at x=70 is 50 yd deep and 10 yd off centre
 let s=stats(g);assert.equal(s.p0.pulls,1);assert.equal(s.p0.pullVertical,50);assert.equal(s.p0.pullHorizontal,10);assert.equal(s.p0.pullsOutOfBounds,0);
 const brick=pullMetrics({side:'them',location:{x:FIELD.length-FIELD.endzone-20,y:FIELD.width/2}},{direction:1},FIELD);assert.equal(brick.outOfBounds,true);
 g.events.push(event('point_end',{winner:'us'}));g.events.push(event('point_start',{line:team.players.map(p=>p.id),starting:'D',direction:-1}));g.events.push(event('possession_start',{side:'them',playerId:null,pullerId:'p0',location:{x:FIELD.endzone+20,y:FIELD.width/2}}));
 s=stats(g);assert.equal(s.p0.pulls,2);assert.equal(s.p0.pullsOutOfBounds,1);assert.equal(s.p0.pullVertical,50);});
