const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const signed=value=>`${value>0?'+':''}${Math.abs(value)<.05?'0.0':value.toFixed(1)}`;
export function adjustedCell(entry,side,playerId){
 if(entry.status==='pending')return '<span aria-label="Calculating adjusted rating">…</span>';
 const r=entry.result?.[side]?.ratings[playerId];
 return r?.value==null?'—':`${signed(r.value)}${r.status==='partly-confounded'?'<sup>†</sup>':''}`;
}
function validationText(v){
 if(v.status!=='available')return `Prediction check unavailable. ${esc(v.reason)}`;
 return `Whole-game prediction check: ${v.improvement>0?'player effects improved predictions':'player effects did not improve predictions'} across ${v.games} held-out games (${v.points} points). Log loss: ${v.adjustedLoss.toFixed(3)} with player effects vs ${v.baselineLoss.toFixed(3)} with game/opponent context alone; lower is better. Shrinkage is selected inside each training fold. This is an exploratory comparison, not evidence of causation.`;
}
export function adjustedSummary(entry,playerId,playerName){
 if(entry.status==='pending')return '<h3>Adjusted +/-</h3><p role="status">Calculating ratings, uncertainty and whole-game validation… You can use the matched tables below while this runs.</p>';
 if(entry.status==='error')return `<h3>Adjusted +/-</h3><p role="alert">Adjusted ratings unavailable: ${esc(entry.error)}</p>`;
 const result=entry.result,card=(key,label,direction)=>{
  const s=result[key],r=s.ratings[playerId],c=s.coverage;
  return `<section class="adjusted-rating-card"><h4>${label}</h4><p class="adjusted-estimate">${r?.value==null?'—':`${signed(r.value)} <small>pp</small>`}</p><p>${r?.interval?`Approx. 95% credible interval: <strong>${signed(r.interval[0])} to ${signed(r.interval[1])} pp</strong>. ${direction}`:r?'No within-game on/off variation: this player’s effect cannot be estimated separately.':'No eligible points for this player on this start.'}</p>${r?.interval?`<p>${r.status==='partly-confounded'?`<strong>† Partly confounded with other lineups.</strong> ${r.confoundedWith.length?`Always plays with ${r.confoundedWith.map(id=>esc(playerName(id))).join(', ')} in these eligible points. `:''}The data cannot fully separate this player’s contribution. `:''}Data reduce the prior variance of this player’s replacement contrast by ${(r.uncertaintyReduction*100).toFixed(0)}%. ${r.uncertaintyReduction<.5?'Most uncertainty still comes from the prior. ':''}${r.points} player-on points in ${r.games} game${r.games===1?'':'s'}.</p><p>Prior sensitivity: ${signed(r.sensitivity[0])} to ${signed(r.sensitivity[1])} pp across the three shrinkage settings. Selected prior SD: ${s.priorSD} log-odds${s.priorScores.length?' (whole-game cross-validation)':' (provisional default; too few games to tune)'}.</p>`:''}<p>Model coverage: ${c.used}/${c.completed} completed ${key==='hold'?'O':'D'} points. Excluded: ${c.incompleteLine} incomplete/invalid lines and ${c.substitution} substitution points. Opponent lineups adjusted on ${c.opponentAdjusted}/${c.used} included points.</p><p class="adjusted-validation">${validationText(s.validation)}</p></section>`;
 };
 return `<h3>Adjusted +/-</h3><p>Estimated change versus an average comparison player, in percentage points. These ratings use all eligible points; there is no 10-point cutoff.</p><div class="adjusted-rating-grid">${card('hold','Adjusted hold +/-','Higher is better.')}${card('opponentHold','Adjusted opp hold +/-','Lower is better.')}</div><details class="matched-calculation"><summary>How are these calculated?</summary><p>Separate logistic models for O and D jointly estimate teammates, opponent context and game difficulty. Lineups are centered within each game: only within-game lineup changes inform player effects. Each completed point with seven known, distinct roster players is used once; points with our-side substitutions are excluded. Opponent player effects are included only when every eligible point on that start in a game has a complete, unsubstituted opponent lineup.</p><p>Gaussian priors shrink uncertain effects toward the comparison-pool average. The pool contains players with within-game on/off variation on that start (${result.hold.comparisonPlayers.length} on O; ${result.opponentHold.comparisonPlayers.length} on D). Ratings compare each player with the average of the other pool members at the same game contexts, weighted by included points. This is a standardized comparison; position, gender, fatigue and unrecorded matchup differences are not controlled.</p><p>Intervals use a joint Laplace approximation to the posterior, conditional on the selected prior. They include teammate and game-context covariance, but not uncertainty about the model or prior selection, and can be optimistic when points remain dependent within games. Variance reduction describes how much the data informed a contrast; it is not the probability that a rating is correct. Prior sensitivity and whole-game validation are shown alongside it. Three candidate player prior SDs (${result.priorCandidates.join(', ')} log-odds) are modeling assumptions, not research-established ultimate constants.</p><p>The 6/5/4-player matched comparisons below remain descriptive supporting evidence. They are overlapping samples and are not blended into the adjusted rating.</p></details>`;
}
