import {FIELD,uid,emptyData,event,other,pointsOf,gameState,passMetrics,statsFor,advancedStatsFor,offensiveScoringEfficiency,teamRates,STAT_COLUMNS,validateData,mergeData,playersForGroup,lineSlots} from './core.js';
import {readStattoZip,convertStatto} from './statto.js';
import {readStore,writeStore} from './storage.js';
const $=s=>document.querySelector(s), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let data=emptyData(),view='games',teamId=null,gameId=null,tab='track',reviewPoint=null,reviewIndex=null,highlightedPassId=null,statsSort='name',statsDesc=false,minPoints=0,selectedGameIds=[],huckYards=35,mergeTeamId=null,mergePlayerIds=[],saveLabel='Saved on this device',toastTimer;
const team=()=>data.teams.find(t=>t.id===teamId), game=()=>data.games.find(g=>g.id===gameId);
const secondaryEdgeSettings=()=>({previousShare:data.settings?.secondaryPreviousShare??.3,previousPreviousShare:data.settings?.secondaryPreviousPreviousShare??.1,includeInTotal:data.settings?.includeSecondaryInTotal??false});
const icons={games:'<rect x="3" y="4" width="18" height="16" rx="2"/><path d="M8 4v16m8-16v16M3 12h18"/>',teams:'<circle cx="9" cy="8" r="3"/><path d="M3 21v-3a6 6 0 0 1 12 0v3m0-16a3 3 0 0 1 0 6m3 10v-3a6 6 0 0 0-2-4"/>',stats:'<path d="M5 20v-7m7 7V4m7 16V9"/>',data:'<path d="M12 3v12m-4-4 4 4 4-4M4 16v5h16v-5"/>'};
const icon=name=>`<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round">${icons[name]||icons.games}</svg>`;
const initials=name=>String(name||'FB').split(/\s+/).slice(0,2).map(w=>w[0]).join('').toUpperCase();
const date=s=>{try{return new Date(s).toLocaleDateString(undefined,{month:'short',day:'numeric',year:'numeric'});}catch{return '';}};
const fmt=n=>Number.isInteger(n)?String(n):Number(n).toFixed(1);
const fixedFmt=(n,digits)=>(Number(n)||0).toFixed(digits);
function toast(message){$('#toast').textContent=message;$('#toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),4500);}
async function persist(){saveLabel='Saving…';try{await writeStore(data);saveLabel='Saved on this device';}catch(e){saveLabel='Not saved — export now';toast('Local save failed. Export your JSON now to preserve this session.');}document.querySelectorAll('.save-state').forEach(el=>el.textContent=saveLabel);}
async function commit(){if(game())game().updatedAt=new Date().toISOString();await persist();render();}
function closeModal(){$('#modal').close();$('#modal').innerHTML='';}
function modal(title,content){const d=$('#modal');d.innerHTML=`<div class="modal-head"><h2>${esc(title)}</h2><button class="ghost" data-close aria-label="Close dialog">✕</button></div><div class="modal-body">${content}</div>`;if(!d.open)d.showModal();d.querySelector('[data-close]').onclick=closeModal;d.querySelectorAll('[data-cancel]').forEach(b=>b.onclick=closeModal);}
function playerName(id,g=game()){if(!id)return 'Unknown';const p=data.teams.flatMap(t=>t.players).find(p=>p.id===id)||g?.opponents.find(p=>p.id===id);return p?.name||'Unknown';}
function playerLabel(p){return `${p.number!==''&&p.number!=null?'#'+p.number+' · ':''}${p.name}`;}
function options(players,selected=null,unknown=true){return `${unknown?'<option value="">Unknown / unassigned</option>':''}${players.map(p=>`<option value="${esc(p.id)}" ${selected===p.id?'selected':''}>${esc(playerLabel(p))}</option>`).join('')}`;}
function teamFilter(){return `<select class="filter" id="team-filter" aria-label="Filter by team"><option value="">All teams</option>${data.teams.map(t=>`<option value="${esc(t.id)}" ${t.id===teamId?'selected':''}>${esc(t.name)}</option>`).join('')}</select>`;}
function eligibleGames(){return data.games.filter(g=>!teamId||g.teamId===teamId);}
function relevantGames(){const eligible=eligibleGames();return selectedGameIds.length?eligible.filter(g=>selectedGameIds.includes(g.id)):eligible;}
function gameSelectionButton(){const label=selectedGameIds.length?`${selectedGameIds.length} games selected`:'All games';return `<button data-action="select-games">▦ ${label}</button>`;}
function render(){
 const activeTeam=team(),g=game();
 $('#app').innerHTML=`<div class="shell"><aside class="sidebar"><div><div class="brand"><svg viewBox="0 0 32 32" fill="none" stroke="#ddec87" stroke-width="1.8"><ellipse cx="16" cy="16" rx="15" ry="6" transform="rotate(-32 16 16)"/><path d="M6 25 26 7"/></svg>fieldbook<span style="font-size:12px;align-self:flex-start;margin-top:3px">↗</span></div><div class="brand-sub">ULTIMATE, RECORDED</div></div><nav class="nav">${[['games','Games'],['stats','Player Stats'],['teams','Players'],['data','Import & export']].map(([v,label])=>`<button data-nav="${v}" class="${view===v||view==='game'&&v==='games'?'active':''}">${icon(v)}${label}</button>`).join('')}</nav><div><div class="side-label">Your teams</div><div class="team-nav">${data.teams.map(t=>`<button data-team="${esc(t.id)}" class="${t.id===teamId?'chosen':''}"><span class="monogram">${esc(initials(t.name))}</span>${esc(t.name)}</button>`).join('')}<button data-action="new-team">＋ Create team</button></div></div><div class="side-bottom"><span class="dot"></span>Ready for the sideline<br>Offline first. Every play is yours.<br><button class="ghost" data-action="help" style="color:#c0cfb4;padding:10px 0;font-size:11px">How Fieldbook works ↗</button></div></aside><main class="main"><header class="topbar"><div class="breadcrumb">Your fieldbook <span style="margin:0 9px">/</span> <strong>${view==='game'?esc(g?.opponent||'Game'):({games:'Games',teams:'Players',stats:'Player Stats',data:'Data library'})[view]}</strong></div><div class="top-actions"><span class="save-state">${esc(saveLabel)}</span><button data-action="import">↓ Import</button><button data-action="export">↑ Export JSON</button></div></header><div id="content">${view==='games'?gamesPage():view==='teams'?teamsPage():view==='stats'?statsPage():view==='data'?dataPage():g?gamePage():gamesPage()}</div></main></div>`;
 bind();
}
function gamesPage(){const games=relevantGames(),allGames=eligibleGames(),pct=(n,d)=>d?`${(n/d*100).toFixed(1)}%`:'—',summary=rates=>[['Hold rate',pct(rates.holds,rates.offense)],['Clean hold rate',pct(rates.cleanHolds,rates.offense)],['Turn rate',pct(rates.turns,rates.defense)],['Break rate',pct(rates.breaks,rates.defense)],['Huck rate',pct(rates.huckCompletions,rates.huckAttempts)]],cards=(rates,interactive=false)=>summary(rates).map(([label,value],index)=>index===4&&interactive?`<div class="card summary"><label>${label}</label><div class="value">${value}</div><small>over <input class="huck-input" id="huck-yards" type="number" min="0" step="1" value="${huckYards}" aria-label="Huck distance threshold"> yd <button class="rate-chart-button" data-action="huck-chart">Chart</button></small></div>`:`<div class="card summary"><label>${label}</label><div class="value">${value}</div></div>`).join(''),selected=selectedGameIds.length>0,rates=teamRates(games,huckYards),allRates=teamRates(allGames,huckYards);
 return `<div class="page-heading"><div><p class="eyebrow">The season, one point at a time</p><h1>${team()?esc(team().name):'Your games'}</h1><p class="subtext">Every touch tells the story. Keep the whole game.</p></div><button class="primary" data-action="new-game">＋ New game</button></div><div class="section-head"><h2>${selected?'Selected-game rates':'All-game rates'}</h2><div class="actions">${teamFilter()}${gameSelectionButton()}<button data-action="show-heatmap">Possession heatmap</button></div></div><div class="summary-grid rates-grid">${cards(rates,true)}</div>${selected?`<div class="section-head"><h2>All-game rates</h2></div><div class="summary-grid rates-grid">${cards(allRates)}</div>`:''}<div class="section-head"><h2>Game library <span style="font-size:12px;color:var(--muted);margin-left:8px">${games.length}</span></h2></div>${games.length?`<div class="game-list">${[...games].sort((a,b)=>b.date.localeCompare(a.date)).map(g=>{const t=data.teams.find(t=>t.id===g.teamId),s=gameState(g).score;return `<button class="card game-row" data-game="${esc(g.id)}"><span class="monogram">${esc(initials(t?.name))}</span><div class="match"><strong>${esc(t?.name)} <span style="font-weight:400;color:var(--muted)">vs</span> ${esc(g.opponent)}</strong><small>${date(g.date)} · ${pointsOf(g).length} points</small></div>${g.source?'<span class="badge imported">Statto import</span>':''}<span class="badge ${!g.finished?'live':''}">${g.finished?'Final':'In progress'}</span><div class="score-mini">${s[0]} <span style="color:#b4bcac">–</span> ${s[1]}</div><span style="color:#8d9b80">↗</span></button>`;}).join('')}</div>`:`<div class="card empty"><div class="field-icon">▱</div><h2>Your next game starts here</h2><p>Create a team and roster, then track every pass on the pitch. Already use Statto? Bring your history with you.</p><div class="actions" style="justify-content:center"><button class="primary" data-action="new-team">Create your first team</button><button data-action="import">Import a Statto file</button></div></div>`}<p class="library-note">◎ Stored on this device · Share a JSON export to combine games from other scorekeepers.</p>`;}
function teamsPage(){return `<div class="page-heading"><div><p class="eyebrow">People make the game</p><h1>Players</h1><p class="subtext">Build your roster. Pick your seven when it’s time to play.</p></div><button class="primary" data-action="new-team">＋ Create team</button></div>${(team()?[team()]:data.teams).map(t=>{const selected=mergeTeamId===t.id?mergePlayerIds:[];return `<section class="card card-pad" style="margin-bottom:20px"><div class="section-head"><div class="actions"><span class="monogram">${esc(initials(t.name))}</span><h2>${esc(t.name)}</h2><span class="badge">${t.players.length} players</span></div><div class="actions"><button data-roster="${esc(t.id)}">＋ Add players</button><button data-roster-export="${esc(t.id)}">Export roster</button></div></div><div class="roster-tools"><small>Select exactly two players to merge their history.</small><button data-merge-players="${esc(t.id)}" ${selected.length===2?'':'disabled'}>Merge selected (${selected.length}/2)</button></div><div class="roster-grid">${t.players.map(p=>`<div class="card roster-person ${selected.includes(p.id)?'merge-picked':''}"><span class="jersey">${esc(p.number||'—')}</span><div><strong>${esc(p.name)}</strong><small>Available for selection</small></div><button class="merge-select" data-merge-player="${esc(p.id)}" data-merge-team="${esc(t.id)}" aria-pressed="${selected.includes(p.id)}">${selected.includes(p.id)?'Selected':'Select'}</button></div>`).join('')}</div>${!t.players.length?'<p class="subtext">Add names and jersey numbers to start selecting lines.</p>':''}</section>`;}).join('')||'<div class="card empty"><h2>A place for your team</h2><p>Create your first team to add players and start a game.</p><button data-action="new-team">Create team</button></div>'}`;}
function seasonAdvancedStats(games,t,huckDistance=huckYards){const rows=new Map(),settings=secondaryEdgeSettings();for(const g of games){const result=advancedStatsFor(g,t,gameOse(g,t),settings.previousShare,settings.previousPreviousShare,settings.includeInTotal,huckDistance);for(const row of result.rows){if(!rows.has(row.id))rows.set(row.id,{...row});else for(const key of ['points','oPoints','dPoints','opportunities','passes','completions','catches','initiated','goals','assists','secondaryAssists','throwaways','drops','blocks','throwDistance','throwGain','catchDistance','catchGain','throwAllowed','receiveAllowed','goalsAllowed','assistsAllowed','targets','forcedThrowaways','huckAttempts','huckCompletions','plusMinus','throwingEdge','receivingEdge','secondaryThrowingEdge','totalEdge'])rows.get(row.id)[key]+=row[key];}}for(const row of rows.values()){row.huckCompletionRate=row.huckAttempts?row.huckCompletions/row.huckAttempts:0;row.totalEdgePerPoint=row.opportunities?row.totalEdge/row.opportunities:0;const touches=row.catches+row.initiated;row.totalEdgePerTouch=touches?row.totalEdge/touches:0;}return [...rows.values()];}
function seasonAdvancedForTeams(games,teams,huckDistance=huckYards){const rows=[];for(const t of teams)rows.push(...seasonAdvancedStats(games.filter(g=>g.teamId===t.id),t,huckDistance));return rows;}
function statsTable(games,teams,{advanced=false,pointsThreshold=0,huckDistance=huckYards}={}){const settings=secondaryEdgeSettings(),rows=(advanced?(games.length===0?statsFor(teams,games,huckDistance).map(r=>({...r,plusMinus:0,throwingEdge:0,receivingEdge:0,secondaryThrowingEdge:0,totalEdge:0,totalEdgePerPoint:0,totalEdgePerTouch:0})):games.length===1?advancedStatsFor(games[0],teams[0],gameOse(games[0],teams[0]),settings.previousShare,settings.previousPreviousShare,settings.includeInTotal,huckDistance).rows:seasonAdvancedForTeams(games,teams,huckDistance)):statsFor(teams,games,huckDistance)).filter(row=>row.points>pointsThreshold);const defenseIncomplete=games.some(g=>g.source?.defenseAvailable===false),edgeKeys=['throwingEdge','receivingEdge','secondaryThrowingEdge','totalEdge'],ratioKeys=['totalEdgePerPoint','totalEdgePerTouch'],display=(key,value)=>ratioKeys.includes(key)?fixedFmt(value,3):edgeKeys.includes(key)?fixedFmt(value,2):key==='huckCompletionRate'?fixedFmt(value*100,1)+'%':fmt(value),header=label=>label.includes(' ')?label.replace(/ (?!.* )/,'<br>'):label;const cols=advanced?[...STAT_COLUMNS,['huckCompletionRate','Huck completion rate'],['plusMinus','+/-'],['throwingEdge','Throw EDGE'],['receivingEdge','Receive EDGE'],['secondaryThrowingEdge','Secondary throwing EDGE'],['totalEdge','Total EDGE'],['totalEdgePerPoint','Total EDGE/pt'],['totalEdgePerTouch','Total EDGE/touch']]:STAT_COLUMNS;const sorted=[...rows].sort((a,b)=>{const av=statsSort==='name'?a.name.toLowerCase():Number(a[statsSort]||0),bv=statsSort==='name'?b.name.toLowerCase():Number(b[statsSort]||0);return (av>bv?1:av<bv?-1:0)*(statsDesc?-1:1);});return `<div class="card table-scroll"><table class="stats-table"><thead><tr><th><button class="table-sort" data-sort="name">Player ${statsSort==='name'?(statsDesc?'↓':'↑'):''}</button></th>${cols.map(([key,label])=>`<th title="${esc(key)}"><button class="table-sort" data-sort="${key}">${header(label)}${statsSort===key?(statsDesc?' ↓':' ↑'):''}${defenseIncomplete&&['throwAllowed','receiveAllowed','goalsAllowed','assistsAllowed','targets','forcedThrowaways'].includes(key)?'*':''}</button></th>`).join('')}</tr></thead><tbody>${sorted.map(r=>`<tr><td class="stat-name"><small>${esc(r.number||'—')}</small>${esc(r.name)}</td>${cols.map(([k])=>`<td>${display(k,r[k])}</td>`).join('')}</tr>`).join('')}</tbody></table></div><p class="stats-help">Click any column heading to sort. All distances in yards. Secondary throwing EDGE uses the Player Stats weights; Total EDGE follows the Player Stats inclusion setting.</p>`;}
function statsPage(){const gs=relevantGames(),ts=team()?[team()]:data.teams,settings=secondaryEdgeSettings();return `<div class="page-heading"><div><p class="eyebrow">From every play to the bigger picture</p><h1>Player statistics</h1><p class="subtext">${gs.length} selected games · Recalculated from your play-by-play.</p></div><div class="actions">${teamFilter()}${gameSelectionButton()}<label class="points-filter">Over <input id="player-min-points" type="number" min="0" step="1" value="${minPoints}" aria-label="Minimum points played"> points</label></div></div><div class="stats-settings edge-settings card"><div><strong>Secondary throwing EDGE</strong><small>Previous thrower · thrower before that</small></div><div class="edge-weights"><input id="secondary-prev" type="number" min="0" max="1" step="0.01" value="${settings.previousShare}" aria-label="Previous thrower weight"><input id="secondary-prev2" type="number" min="0" max="1" step="0.01" value="${settings.previousPreviousShare}" aria-label="Thrower before that weight"></div><label class="inline-check edge-total-check"><input id="include-secondary-total" type="checkbox" ${settings.includeInTotal?'checked':''}> Include in Total EDGE</label><label class="points-filter huck-stats-filter">Huck over <input id="stats-huck-yards" type="number" min="0" step="1" value="${huckYards}" aria-label="Huck distance"> yd</label><button class="primary" id="save-secondary-settings">Update Player Stats</button></div>${statsTable(gs,ts,{advanced:true,pointsThreshold:minPoints,huckDistance:huckYards})}`;}
function gameOse(g,t){if(g?.settings?.ose!=null)return Number(g.settings.ose);return t?.name==='Mischief 2026'?offensiveScoringEfficiency(data.games,t.id):.56;}
function pointScoreLabel(points,index){const score=[0,0];for(let i=0;i<index;i++){if(points[i].winner==='us')score[0]++;if(points[i].winner==='them')score[1]++;}return `${score[0]}-${score[1]}`;}
function possessionHeatmap(teamId){const t=data.teams.find(x=>x.id===teamId),cells=Array.from({length:112},()=>({touch:0,goal:0}));for(const g of data.games.filter(x=>x.teamId===teamId))for(const p of pointsOf(g)){let touches=[];for(const e of p.events){if(e.type==='possession_start'&&e.side==='us')touches.push(e.location);if(e.type==='pass'&&e.side==='us'&&['complete','goal'].includes(e.outcome))touches.push(e.to);if(e.type==='pass'&&e.side==='us'&&e.outcome==='goal'){for(const pt of touches){const i=Math.min(13,Math.max(0,Math.floor(pt.x/5))),j=Math.min(7,Math.max(0,Math.floor(pt.y/5)));cells[j*14+i].touch++;cells[j*14+i].goal++;}touches=[];}if(e.type==='pass'&&e.side==='us'&&!['complete','goal'].includes(e.outcome)){for(const pt of touches){const i=Math.min(13,Math.max(0,Math.floor(pt.x/5))),j=Math.min(7,Math.max(0,Math.floor(pt.y/5)));cells[j*14+i].touch++;}touches=[];}if(e.type==='turnover'&&e.side==='us'){for(const pt of touches){const i=Math.min(13,Math.max(0,Math.floor(pt.x/5))),j=Math.min(7,Math.max(0,Math.floor(pt.y/5)));cells[j*14+i].touch++;}touches=[];}}for(const pt of touches){const i=Math.min(13,Math.max(0,Math.floor(pt.x/5))),j=Math.min(7,Math.max(0,Math.floor(pt.y/5)));cells[j*14+i].touch++;}}
 const max=Math.max(1,...cells.map(c=>c.touch));modal(`Possession heatmap · ${t?.name||'Team'}`,`<p>Touches are possessions initiated plus completed catches. Hover a box for touches and the share of those touches that ended in a goal.</p><div class="heatmap" style="grid-template-columns:repeat(14,1fr)">${cells.map(c=>{const pct=c.touch?c.goal/c.touch:0;return `<div class="heat-cell" title="${Math.round(pct*100)}% goal rate · ${c.touch} touch${c.touch===1?'':'es'}" style="background:rgba(46,96,74,${c.touch?(.12+.75*c.touch/max):.04})"><span>${c.touch?Math.round(pct*100)+'%':''}</span></div>`;}).join('')}</div>`);}
function possessionHeatmapOriented(teamId){
 const t=data.teams.find(x=>x.id===teamId),rows=18,columns=8,cells=Array.from({length:rows*columns},()=>({touch:0,goal:0}));
 const displayDepth=depth=>depth<=20?depth/2:depth<=90?depth-10:80+(depth-90)/2;
 const add=(point,location,goal)=>{if(!location)return;const depth=point.direction===1?110-location.x:location.x,row=Math.min(rows-1,Math.max(0,Math.floor(displayDepth(depth)/5))),col=Math.min(columns-1,Math.max(0,Math.floor(location.y/5))),cell=cells[row*columns+col];cell.touch++;if(goal)cell.goal++;};
 for(const g of data.games.filter(x=>x.teamId===teamId))for(const point of pointsOf(g)){let touches=[];for(const e of point.events){if(e.type==='possession_start'&&e.side==='us')touches.push(e.location);if(e.type==='pass'&&e.side==='us'&&['complete','goal'].includes(e.outcome))touches.push(e.to);if(e.type==='pass'&&e.side==='us'&&e.outcome==='goal'){touches.forEach(location=>add(point,location,true));touches=[];}else if(e.type==='pass'&&e.side==='us'&&!['complete','goal'].includes(e.outcome)){touches.forEach(location=>add(point,location,false));touches=[];}if(e.type==='turnover'&&e.side==='us'){touches.forEach(location=>add(point,location,false));touches=[];}}touches.forEach(location=>add(point,location,false));}
 const max=Math.max(1,...cells.map(c=>c.touch)),color=(c,mode)=>{if(!c.touch)return '#edf0e8';const value=mode==='touch'?Math.sqrt(c.touch/max):c.goal/c.touch,hue=mode==='touch'?210-195*value:230-225*value,light=mode==='touch'?94-44*value:94-42*value;return `hsl(${hue} 78% ${light}%)`;};
 const grid=(mode)=>`<div class="heatmap heatmap-vertical" style="grid-template-columns:repeat(${columns},1fr)"><div class="heat-endzone-label">End zone</div>${mode==='rate'?'<span class="field-line-label label-brick-top">Brick</span><span class="field-line-label label-midfield">Midfield</span><span class="field-line-label label-brick-bottom">Brick</span>':''}${cells.map((c,i)=>{const row=Math.floor(i/columns);if(row<2)return '';const pct=c.touch?c.goal/c.touch:0,val=mode==='touch'?c.touch:(c.touch?Math.round(pct*100)+'%':'');const cls=[row===16?'heat-endzone-bottom':'',row===5||row===11?'heat-brick':'',row===8?'heat-midfield':'',mode==='rate'&&pct>=.9?'heat-text-light':''].filter(Boolean).join(' ');return `<div class="heat-cell ${cls}" data-heat-detail="${i}" style="background:${color(c,mode)}"><span>${val}</span></div>`;}).join('')}</div>`;
 modal(`Possession heatmaps · ${t?.name||'Team'}`,`<p>Attacking end zone is at the top. Each box is 5×5 yards; the ten-yard end zones are proportionally compressed from the tracked 20-yard end zones.</p><div class="heatmap-pair"><section class="heatmap-panel"><h3>Goal rate by touch</h3>${grid('rate')}</section><section class="heatmap-panel"><h3>Total touches</h3>${grid('touch')}</section></div><p class="heatmap-detail" id="heatmap-detail" aria-live="polite">Click any box to show its touches and goal rate.</p>`);
 $('#modal').querySelectorAll('[data-heat-detail]').forEach(cell=>cell.onclick=()=>{const c=cells[Number(cell.dataset.heatDetail)],pct=c.touch?Math.round(c.goal/c.touch*100):0;$('#heatmap-detail').textContent=`${c.touch} touch${c.touch===1?'':'es'} · ${pct}% of those touches ended in a goal.`;});
}
function dataPage(){return `<div class="page-heading"><div><p class="eyebrow">Your games. Your data.</p><h1>A portable playbook</h1><p class="subtext">Bring your history in. Take every detail with you.</p></div></div><div class="data-grid"><section class="card card-pad"><h2>Import your games</h2><p>Open an existing Statto archive or a Fieldbook JSON export. Teams and new games are merged into this library. Existing games are kept, so repeat imports never duplicate or overwrite your work.</p><div><span class="file-format">.statto</span><span class="file-format">.json</span></div><button class="primary" data-action="import">Choose a file</button></section><section class="card card-pad"><h2>Export your library</h2><p>Share rosters before a tournament, then combine separate scorekeepers’ games afterward. The export contains teams, players, ordered events, and original Statto source records where applicable.</p><div><span class="file-format">JSON · version 1</span></div><button class="primary" data-action="export">Export all data</button></section><section class="card card-pad"><h2>Works at the field</h2><p>Your changes save automatically on this device. After the first visit over HTTPS or localhost, the app can reopen offline. You can add it to your tablet’s home screen from your browser’s menu.</p><p>Export regularly to keep a backup. There is no cloud account or automatic cross-device sync in this version.</p></section><section class="card card-pad"><h2>Built around the play-by-play</h2><p>Points, lines, possessions, pass locations, outcomes, and defensive assignments live in one documented event format. Statistics are calculated separately, making it possible to connect another data source later.</p><button data-action="help">View stat definitions</button></section></div>`;}
function fieldSvg(p,events,g,interactive=false,highlightId=null){const f=g.field||FIELD,L=f.length,W=f.width,ez=f.endzone||20,dir=p?.direction||1;
 const draw=events.filter(e=>e.type==='pass');const last=events.filter(e=>e.type==='pass'||e.type==='possession_start').at(-1);const pos=last?.to||last?.location;
 return `<svg class="pitch ${interactive?'':'locked'}" id="pitch" viewBox="-1 -1 ${L+2} ${W+2}" role="img" aria-label="Horizontal ultimate field, 110 by 40 yards. ${interactive?'Tap to record a location.':''}" style="aspect-ratio:${(L+2)/(W+2)}"><defs><pattern id="grass" width="${L/10}" height="${W}" patternUnits="userSpaceOnUse"><rect width="${L/20}" height="${W}" fill="#ffffff" opacity=".035"/></pattern><marker id="arrow" viewBox="0 0 10 10" refX="8" refY="5" markerWidth="2" markerHeight="4" orient="auto-start-reverse"><path d="M0 0 10 5 0 10z" fill="#f1efb5"/></marker></defs><rect width="${L}" height="${W}" fill="#557454"/><rect width="${ez}" height="${W}" fill="#456345"/><rect x="${L-ez}" width="${ez}" height="${W}" fill="#456345"/><rect width="${L}" height="${W}" fill="url(#grass)"/><g fill="none" stroke="#dfe6ca" stroke-width=".25"><rect width="${L}" height="${W}"/><path d="M${ez} 0v${W}M${L-ez} 0v${W}"/><path d="M${L/2} 0v${W}" stroke-dasharray="1.2 1.3" opacity=".6"/>${[ez+20,L-ez-20].map(x=>`<path d="M${x-1} ${W/2}h2m-1-1v2"/>`).join('')}</g><g fill="#d1ddbc" opacity=".35" font-family="sans-serif" font-size="2.2" letter-spacing=".8"><text x="${ez/2}" y="${W/2}" text-anchor="middle" transform="rotate(-90 ${ez/2} ${W/2})">${dir===1?'HOME END':'ATTACKING END'}</text><text x="${L-ez/2}" y="${W/2}" text-anchor="middle" transform="rotate(90 ${L-ez/2} ${W/2})">${dir===1?'ATTACKING END':'HOME END'}</text></g>${draw.map((e,i)=>`<line x1="${e.from.x}" y1="${e.from.y}" x2="${e.to.x}" y2="${e.to.y}" stroke="${e.id===highlightId?'#ffffff':['complete','goal'].includes(e.outcome)?e.side==='us'?'#f1efb5':'#b6d8e1':'#efb183'}" stroke-width="${e.id===highlightId?'1.1':'.45'}" opacity="${e.id===highlightId?1:.4+.6*(i+1)/draw.length}" ${!['complete','goal'].includes(e.outcome)?'stroke-dasharray="1 1"':''} marker-end="url(#arrow)"/><circle cx="${e.to.x}" cy="${e.to.y}" r="${e.id===highlightId?'.58':'.65'}" fill="${e.outcome==='goal'?'#e1ed8a':'#f1efb5'}"/>`).join('')}${pos?`<circle cx="${pos.x}" cy="${pos.y}" r="1.8" fill="#e2ec92" opacity=".24"/><circle cx="${pos.x}" cy="${pos.y}" r=".95" fill="#fbffd9" stroke="#2f4b2f" stroke-width=".35"/>`:''}</svg>`;}
function gamePage(){const g=game(),s=gameState(g),t=data.teams.find(t=>t.id===g.teamId);return `<div class="page-heading tracker-heading"><div class="scoreboard"><div class="club"><small>Your team</small>${esc(t.name)}</div><div class="big-score">${s.score[0]}<span>:</span>${s.score[1]}</div><div class="club"><small>Opponent</small>${esc(g.opponent)}</div></div><div class="actions"><span class="badge ${g.finished?'':'live'}">${g.finished?'Final':'Tracking live'}</span><button data-action="export-game">Export game</button>${!g.finished?'<button data-action="finish">Finish game</button>':'<button data-action="resume">Resume</button>'}<button class="danger" data-action="delete-game">Delete</button></div></div><div class="tabs">${[['track','Pitch tracker'],['plays','Play-by-play'],['stats','Game statistics']].map(([id,title])=>`<button data-tab="${id}" class="${tab===id?'active':''}">${title}</button>`).join('')}</div>${g.importNotes?`<div class="notice">${g.importNotes.map(esc).join(' ')}</div>`:''}${tab==='stats'?`<div class="stats-settings card card-pad"><div><strong>oSE</strong><small>Offensive scoring efficiency used for drops and receiving EDGE</small></div><input id="ose-input" type="number" min="0" max="1" step="0.001" value="${gameOse(g,t).toFixed(3)}"><button class="primary" data-action="save-settings">Update calculations</button></div>${statsTable([g],[t],{advanced:true})}`:tab==='plays'?reviewPage(g):trackerPage(g,s,t)}`;}
function trackerPage(g,s,t){const p=s.point,events=p?.events||[],live=s.active&&!g.finished,label=s.side==='us'?t.name:g.opponent,arrow=(p?.direction||1)===1?'━━━━━━━━▶':'◀━━━━━━━━',latest=events.filter(e=>e.type!=='point_end').at(-1);return `<div class="tracking-layout"><section class="card pitch-card tracker-focus"><div class="pitch-toolbar"><div class="actions"><strong>POINT ${s.points.length||1}</strong>${p?`<span class="badge">${p.starting}</span>`:''}<span class="badge ${live?'live':''}">${g.finished?'Complete':!s.active?'Between points':s.side==='us'?'Our disc':'Opponent disc'}</span></div><div class="actions">${live?'<button data-action="undo" title="Undo last event">↶ Undo</button>':!g.finished?'<button class="primary" data-action="point">Next point</button>':''}</div></div><div class="pitch-wrap"><div class="attack-strip"><span>${arrow}</span> OUR ATTACK <span>${arrow}</span></div>${fieldSvg(p,events,g,live)}<div class="attack-strip bottom"><span>${arrow}</span> OUR ATTACK <span>${arrow}</span></div></div><div class="pitch-instruction"><p>${g.finished?'Game complete.':!s.active?'Choose the players for the next point.':s.needsPickup?`Tap where ${esc(label)} takes possession.`:`<strong>${esc(playerName(s.holder))}</strong> has the disc · tap the destination, then the receiver.`}</p><small>${latest?esc(feedSummary(latest,g)):'Tap the field to begin.'}</small></div></section></div>`;}
function feedSummary(e,g){if(e.type==='possession_start')return `${playerName(e.playerId,g)} took possession`;if(e.type==='pass')return `${playerName(e.throwerId,g)} → ${playerName(e.receiverId,g)} · ${e.outcome}`;if(e.type==='turnover')return e.reason.replaceAll('_',' ');return 'Point recorded';}
function feedRow(e,p,g,i){let title='',titleHtml='',detail='',distance='';if(e.type==='possession_start'){title=`${playerName(e.playerId,g)} takes possession`;detail=e.side==='us'?'Our possession':'Opponent possession';}else if(e.type==='pass'){titleHtml=`${esc(playerName(e.throwerId,g))} → <button class="receiver-hold" data-receiver-edit="${esc(e.id)}" title="Click to change receiver">${esc(playerName(e.receiverId,g))}</button>`;detail=({complete:'Completed pass',goal:'Goal · assist',drop:'Drop',throwaway:'Throwaway',block:'Block',stall:'Stall out'})[e.outcome];if(e.side==='them')detail+=' · opponent';if(e.markerId)detail+=` · marker: ${playerName(e.markerId,g)}`;if(e.receiverDefenderId)detail+=` · receiver defender: ${playerName(e.receiverDefenderId,g)}`;const m=passMetrics(e,p);distance=`${m.distance.toFixed(1)} yd · ${m.gain>=0?'+':''}${m.gain.toFixed(1)} gain`;}else if(e.type==='turnover'){title=e.reason==='block'?`${playerName(e.blockerId,g)} · block`:'Turnover';detail=e.reason.replaceAll('_',' ');}else{title=e.winner==='us'?'Our point':'Opponent point';detail='Point result';}return `<div class="feed-row ${e.id===highlightedPassId?'highlighted':''}" ${e.type==='pass'?`data-highlight-pass="${esc(e.id)}"`:''}><span class="event-no">${String(i+1).padStart(2,'0')}</span><span class="event-icon">${e.outcome==='goal'?'★':e.type==='possession_start'?'○':'↗'}</span><div class="event-copy">${titleHtml||esc(title)}<small>${esc(detail)}</small></div><span class="distance">${distance}</span>${e.type==='pass'?`<button data-edit="${esc(e.id)}" aria-label="Correct pass">Edit</button>`:''}</div>`;}
function reviewPage(g){const points=pointsOf(g);const p=points.find(p=>p.id===reviewPoint)||points.at(-1);if(!p)return '<div class="card empty"><h2>No plays yet</h2><p>Start a point on the pitch tracker.</p></div>';reviewPoint=p.id;const es=p.events.filter(e=>e.type!=='point_end'),limit=reviewIndex==null?es.length:Math.min(reviewIndex,es.length);return `<div class="review-controls"><label for="review-point">Review</label><select id="review-point">${points.map((x,i)=>`<option value="${esc(x.id)}" ${x.id===p.id?'selected':''}>${pointScoreLabel(points,i)} · Point ${i+1} · ${x.starting} · ${x.winner==='us'?'Scored':x.winner==='them'?'Conceded':'In progress'}</option>`).join('')}</select><button data-action="undo">↶ Undo latest event</button></div><section class="card pitch-card"><div class="pitch-wrap">${fieldSvg(p,es.slice(0,limit),g,false,highlightedPassId)}<div class="pitch-legend"><span>Play ${limit} of ${es.length}</span><span>Click a pass below to highlight it</span></div></div><div class="card-pad" style="padding:12px 20px"><input id="replay" aria-label="Scrub play-by-play" type="range" min="0" max="${es.length}" value="${limit}"></div></section><div class="play-feed">${es.slice(0,limit).map((e,i)=>feedRow(e,p,g,i)).join('')}</div>`;}
function bind(){
 document.querySelectorAll('[data-nav]').forEach(b=>b.onclick=()=>{view=b.dataset.nav;gameId=null;render();});
 document.querySelectorAll('[data-team]').forEach(b=>b.onclick=()=>{teamId=b.dataset.team;view='games';gameId=null;render();});
 document.querySelectorAll('[data-game]').forEach(b=>b.onclick=()=>{gameId=b.dataset.game;teamId=game().teamId;view='game';tab=game().finished?'plays':'track';reviewPoint=null;reviewIndex=null;highlightedPassId=null;render();});
 document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{tab=b.dataset.tab;render();});
 document.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>actions[b.dataset.action]?.());
 document.querySelectorAll('[data-roster]').forEach(b=>b.onclick=()=>addPlayers(b.dataset.roster));
 document.querySelectorAll('[data-roster-export]').forEach(b=>b.onclick=()=>download({...emptyData(),teams:[data.teams.find(t=>t.id===b.dataset.roster)]},'roster'));
 document.querySelectorAll('[data-heatmap]').forEach(b=>b.onclick=()=>possessionHeatmapOriented(b.dataset.heatmap));
 document.querySelectorAll('[data-merge-player]').forEach(b=>b.onclick=()=>{const id=b.dataset.mergePlayer,selectedTeam=b.dataset.mergeTeam;if(mergeTeamId!==selectedTeam){mergeTeamId=selectedTeam;mergePlayerIds=[];}if(mergePlayerIds.includes(id))mergePlayerIds=mergePlayerIds.filter(playerId=>playerId!==id);else if(mergePlayerIds.length<2)mergePlayerIds.push(id);else toast('Select only two players to merge.');render();});
 document.querySelectorAll('[data-merge-players]').forEach(b=>b.onclick=()=>mergePlayers(b.dataset.mergePlayers));
 document.querySelectorAll('[data-sort]').forEach(b=>b.onclick=()=>{const table=document.querySelector('.table-scroll'),left=table?.scrollLeft||0;if(statsSort===b.dataset.sort)statsDesc=!statsDesc;else{statsSort=b.dataset.sort;statsDesc=true;}render();requestAnimationFrame(()=>{const next=document.querySelector('.table-scroll');if(next)next.scrollLeft=left;});});
 if($('#save-settings'))$('#save-settings').onclick=async()=>{const g=game();g.settings={...(g.settings||{}),ose:Number($('#ose-input').value)};await commit();toast('Game statistics updated.');};
 if($('#save-secondary-settings'))$('#save-secondary-settings').onclick=async()=>{const left=document.querySelector('.table-scroll')?.scrollLeft||0;data.settings={...(data.settings||{}),secondaryPreviousShare:Number($('#secondary-prev').value),secondaryPreviousPreviousShare:Number($('#secondary-prev2').value),includeSecondaryInTotal:$('#include-secondary-total').checked};huckYards=Math.max(0,Number($('#stats-huck-yards').value)||0);await persist();render();requestAnimationFrame(()=>{const table=document.querySelector('.table-scroll');if(table)table.scrollLeft=left;});toast('Player Stats calculations updated.');};
 document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>editPass(b.dataset.edit));
 if($('#team-filter'))$('#team-filter').onchange=e=>{teamId=e.target.value||null;render();};
 if($('#player-min-points'))$('#player-min-points').onchange=e=>{minPoints=Math.max(0,Math.floor(Number(e.target.value)||0));render();};
 if($('#huck-yards'))$('#huck-yards').onchange=e=>{huckYards=Math.max(0,Number(e.target.value)||0);render();};
 if($('#review-point'))$('#review-point').onchange=e=>{reviewPoint=e.target.value;reviewIndex=null;highlightedPassId=null;render();};
 if($('#replay'))$('#replay').oninput=e=>{reviewIndex=Number(e.target.value);highlightedPassId=null;render();};
 bindPassInteractions();
 if($('#pitch')&&view==='game'&&tab==='track'&&gameState(game()).active&&!game().finished)$('#pitch').onclick=e=>{const svg=e.currentTarget,p=svg.createSVGPoint();p.x=e.clientX;p.y=e.clientY;const v=p.matrixTransform(svg.getScreenCTM().inverse()),f=game().field;recordLocation({x:Math.max(0,Math.min(f.length,v.x)),y:Math.max(0,Math.min(f.width,v.y))});};
}
function bindPassInteractions(){
 document.querySelectorAll('[data-highlight-pass]').forEach(row=>row.onclick=e=>{if(e.target.closest('[data-edit],[data-receiver-edit]'))return;highlightedPassId=row.dataset.highlightPass;render();});
 document.querySelectorAll('[data-receiver-edit]').forEach(button=>button.onclick=e=>{e.stopPropagation();changeReceiver(button.dataset.receiverEdit);});
}
function selectGames(){const games=eligibleGames();modal('Choose games for statistics',`<form id="game-selection-form"><p>Select the games used for the Games rates and player statistics. Clearing the selection uses every eligible game.</p><div class="game-checks">${games.length?games.map(g=>{const t=data.teams.find(t=>t.id===g.teamId),s=gameState(g).score;return `<label><input type="checkbox" value="${esc(g.id)}" ${selectedGameIds.includes(g.id)?'checked':''}> <strong>${esc(t?.name)} vs ${esc(g.opponent)}</strong><small>${date(g.date)} · ${s[0]}–${s[1]}</small></label>`;}).join(''):'<p>No games match this team filter.</p>'}</div><div class="modal-foot"><button type="button" id="clear-game-selection">Use all games</button><button type="button" data-cancel>Cancel</button><button class="primary" type="submit">Apply selection</button></div></form>`);$('#clear-game-selection').onclick=()=>{selectedGameIds=[];closeModal();render();};$('#game-selection-form').onsubmit=e=>{e.preventDefault();selectedGameIds=[...$('#game-selection-form').querySelectorAll('input:checked')].map(input=>input.value);closeModal();render();};}
function showHeatmap(){if(team()){possessionHeatmapOriented(teamId);return;}modal('Choose a team',`<p>Possession heatmaps are calculated for one team at a time.</p><div class="player-picker">${data.teams.map(t=>`<button data-heatmap-team="${esc(t.id)}">${esc(t.name)}</button>`).join('')}</div><div class="modal-foot"><button data-cancel>Cancel</button></div>`);$('#modal').querySelectorAll('[data-heatmap-team]').forEach(button=>button.onclick=()=>possessionHeatmapOriented(button.dataset.heatmapTeam));}
function huckChart(){const values=Array.from({length:9},(_,i)=>35+i*5).map(yards=>({yards,...teamRates(relevantGames(),yards)})),width=480,height=220,pad={left:38,right:16,top:16,bottom:35},plotW=width-pad.left-pad.right,plotH=height-pad.top-pad.bottom,x=i=>pad.left+i*plotW/(values.length-1),y=rate=>pad.top+(1-rate)*plotH,points=values.map((v,i)=>v.huckAttempts?`${x(i)},${y(v.huckCompletions/v.huckAttempts)}`:null).filter(Boolean).join(' ');
 const guide=[0,.25,.5,.75,1].map(rate=>`<g><line x1="${pad.left}" x2="${width-pad.right}" y1="${y(rate)}" y2="${y(rate)}" stroke="#d8dfd3"/><text x="${pad.left-7}" y="${y(rate)+4}" text-anchor="end" font-size="10" fill="#718070">${Math.round(rate*100)}%</text></g>`).join(''),labels=values.map((v,i)=>`<text x="${x(i)}" y="${height-12}" text-anchor="middle" font-size="10" fill="#718070">${v.yards}</text>`).join(''),dots=values.map((v,i)=>v.huckAttempts?`<circle cx="${x(i)}" cy="${y(v.huckCompletions/v.huckAttempts)}" r="4" fill="#183c30"/>`: `<circle cx="${x(i)}" cy="${y(0)}" r="3" fill="#b9c2b4"/>`).join('');
 modal('Huck rate by distance',`<p>Completed throws divided by attempts longer than each listed threshold, using the current game selection.</p><svg class="huck-chart" viewBox="0 0 ${width} ${height}" role="img" aria-label="Huck rate from 35 to 75 yards">${guide}<polyline points="${points}" fill="none" stroke="#70953e" stroke-width="3" stroke-linejoin="round" stroke-linecap="round"/>${dots}${labels}<text x="${width/2}" y="${height-1}" text-anchor="middle" font-size="10" fill="#718070">yards</text></svg><div class="huck-chart-values">${values.map(v=>`<span><strong>${v.yards} yd</strong>${v.huckAttempts?`${(v.huckCompletions/v.huckAttempts*100).toFixed(1)}% · ${v.huckCompletions}/${v.huckAttempts}`:'No attempts'}</span>`).join('')}</div><div class="modal-foot"><button data-cancel class="primary">Done</button></div>`);
}
function replacePlayerReferences(value,from,to){const fields=new Set(['line','opponentLine']);const refs=new Set(['playerId','throwerId','receiverId','markerId','receiverDefenderId','blockerId','opponentMarkerId','opponentReceiverDefenderId']);for(const [key,current] of Object.entries(value)){if(fields.has(key)&&Array.isArray(current))value[key]=[...new Set(current.map(id=>id===from?to:id))];else if(refs.has(key)&&current===from)value[key]=to;}}
function mergePlayers(id){const t=data.teams.find(item=>item.id===id),selected=mergeTeamId===id?mergePlayerIds:[];if(!t||selected.length!==2)return;const players=selected.map(playerId=>t.players.find(player=>player.id===playerId));if(players.some(player=>!player))return;modal('Merge player histories?',`<form id="merge-players-form"><p><strong>This cannot be undone.</strong> The selected players’ past points, passes, and groups will be combined under one roster entry.</p><p>You can save a backup before continuing.</p><label class="field" for="merge-keeper">Keep this player</label><select id="merge-keeper">${players.map(player=>`<option value="${esc(player.id)}">${esc(playerLabel(player))}</option>`).join('')}</select><div class="modal-foot"><button type="button" id="export-before-merge">Export data first</button><button type="button" data-cancel>Cancel</button><button class="danger" type="submit">Merge permanently</button></div></form>`);$('#export-before-merge').onclick=()=>download(data,'before-player-merge');$('#merge-players-form').onsubmit=async event=>{event.preventDefault();const keep=$('#merge-keeper').value,remove=selected.find(playerId=>playerId!==keep);for(const game of data.games){for(const item of game.events)replacePlayerReferences(item,remove,keep);game.opponents=(game.opponents||[]).filter(player=>player.id!==remove);for(const player of game.opponents)if(player.id===keep)player.id=keep;}for(const group of t.groups||[])group.playerIds=[...new Set(group.playerIds.map(playerId=>playerId===remove?keep:playerId))];t.players=t.players.filter(player=>player.id!==remove);mergePlayerIds=[];mergeTeamId=null;closeModal();await persist();render();toast('Player histories merged.');};}
function newTeam(){modal('Create your team',`<form id="team-form"><label class="field" for="team-name">Team name</label><input id="team-name" placeholder="e.g. Mischief 2026" required maxlength="100" autofocus><label class="field" for="team-players">Roster (optional)</label><textarea id="team-players" placeholder="One player per line. Add a number after a comma.&#10;Alex Chen, 12&#10;Sam Rivera, 7"></textarea><div class="modal-foot"><button type="button" data-cancel>Cancel</button><button class="primary" type="submit">Create team</button></div></form>`);$('#team-form').onsubmit=async e=>{e.preventDefault();const name=$('#team-name').value.trim();if(!name)return;const t={id:uid(),name,players:parsePlayers($('#team-players').value),groups:[]};data.teams.push(t);teamId=t.id;view='teams';closeModal();await commit();};}
function parsePlayers(text){return text.split('\n').map(l=>l.trim()).filter(Boolean).map(l=>{const parts=l.split(',');return {id:uid(),name:parts[0].trim(),number:parts.slice(1).join(',').trim().replace(/^#/,'')};}).filter(p=>p.name);}
function addPlayers(id){const t=data.teams.find(t=>t.id===id);modal(`Add players · ${t.name}`,`<form id="roster-form"><p>One player per line; optional jersey number after a comma.</p><textarea id="roster-input" placeholder="Alex Chen, 12&#10;Sam Rivera, 7" required autofocus></textarea><div class="modal-foot"><button type="button" data-cancel>Cancel</button><button type="submit" class="primary">Add to roster</button></div></form>`);$('#roster-form').onsubmit=async e=>{e.preventDefault();t.players.push(...parsePlayers($('#roster-input').value));closeModal();await commit();};}
function newGame(){if(!data.teams.length){newTeam();return;}modal('Start a new game',`<form id="game-form"><label class="field" for="game-team">Your team</label><select id="game-team">${data.teams.map(t=>`<option value="${esc(t.id)}" ${t.id===teamId?'selected':''}>${esc(t.name)}</option>`).join('')}</select><div class="form-grid"><div><label class="field" for="opponent-team">Opponent</label><select id="opponent-team"><option value="custom">Enter a team name</option>${data.teams.map(t=>`<option value="${esc(t.id)}">${esc(t.name)}</option>`).join('')}</select><input id="opponent" placeholder="Opponent team name" required maxlength="100" style="margin-top:8px"></div><div><label class="field" for="game-date">Game date</label><input id="game-date" type="date" value="${new Date().toLocaleDateString('en-CA')}" required></div></div><p>Selecting an existing opponent makes its roster available when choosing the opponent’s line.</p><div class="modal-foot"><button type="button" data-cancel>Cancel</button><button class="primary" type="submit">Create game →</button></div></form>`);const opponentSelect=$('#opponent-team'),opponentInput=$('#opponent');opponentSelect.onchange=()=>{const custom=opponentSelect.value==='custom';opponentInput.hidden=!custom;opponentInput.required=custom;if(!custom)opponentInput.value='';};$('#game-form').onsubmit=async e=>{e.preventDefault();teamId=$('#game-team').value;const opponentTeam=data.teams.find(t=>t.id===opponentSelect.value);if(opponentTeam?.id===teamId){toast('Choose a different team as the opponent.');return;}const opponent=opponentTeam?.name||opponentInput.value.trim();if(!opponent)return;const g={id:uid(),teamId,opponent,opponentTeamId:opponentTeam?.id||null,date:$('#game-date').value+'T12:00:00',field:{...FIELD},finished:false,opponents:(opponentTeam?.players||[]).map(player=>({...player})),events:[],updatedAt:new Date().toISOString()};data.games.push(g);gameId=g.id;view='game';tab='track';closeModal();await commit();selectLine();};}
function selectLine(draft={}){
 const g=game(),s=gameState(g),t=team();if(s.active)return;t.groups??=[];
 let selected=[...(draft.selected??s.point?.line??[])],opponentSelected=[...(draft.opponentSelected??s.point?.opponentLine??[])],starting=draft.starting??s.nextStarting,direction=draft.direction??s.nextDirection,groupId=draft.groupId??'all';
 if(groupId!=='all'&&!t.groups.some(group=>group.id===groupId))groupId='all';
 const groupButtons=`<button data-line-group="all" class="${groupId==='all'?'selected':''}">All players</button>${t.groups.map(group=>`<button data-line-group="${esc(group.id)}" class="${groupId===group.id?'selected':''}">${esc(group.name)} <span>${group.playerIds.length}</span></button>`).join('')}`;
 modal(`Point ${s.points.length+1} · choose the lines`,`<p>${s.point?.winner?`${s.point.winner==='us'?'Your team':'Your opponent'} scored. Starting on ${starting} is selected automatically.`:'Choose whether your team receives or pulls to start the game.'} Unfilled positions are recorded as Unknown.</p><div class="form-grid"><div><label class="field">Starting possession</label><div class="segmented"><button data-start="O" class="${starting==='O'?'selected':''}">Offense · receive</button><button data-start="D" class="${starting==='D'?'selected':''}">Defense · pull</button></div></div><div><label class="field">Our attacking direction</label><div class="segmented"><button data-dir="-1" class="${direction===-1?'selected':''}">← Left</button><button data-dir="1" class="${direction===1?'selected':''}">Right →</button></div></div></div><div class="section-head line-heading"><h3>${esc(t.name)} · <span id="line-count">${selected.length}</span> selected</h3><button class="ghost" id="clear-line">Clear</button></div><div class="selected-line line-slots" id="selected-line"></div><div class="group-filter" aria-label="Filter roster by player group">${groupButtons}<button id="manage-line-group" ${groupId==='all'?'hidden':''}>Manage group</button><button id="new-line-group">＋ New group</button></div><div class="player-picker" id="line-player-picker"></div><p class="group-empty" id="group-empty" hidden>No players are in this group yet.</p><div class="section-head opponent-heading"><h3>${esc(g.opponent)} · <span id="opponent-line-count">${opponentSelected.length}</span> selected</h3><button class="ghost" id="clear-opponent-line">Clear</button></div><div class="selected-line line-slots" id="selected-opponent-line"></div>${g.opponents.length?`<div class="player-picker compact-picker" id="opponent-player-picker">${g.opponents.map(player=>`<button data-opponent-player="${esc(player.id)}"><span class="num">${esc(player.number||'—')}</span>${esc(player.name)}</button>`).join('')}</div>`:'<p class="group-empty">No opponent roster selected. All seven positions will remain Unknown.</p>'}<div class="modal-foot"><span class="hint">You can start with any number of known players.</span><button class="primary" id="start-point">Start point →</button></div>`);
 const draftState=()=>({selected,opponentSelected,starting,direction,groupId});
 const slotMarkup=(roster,ids,attribute)=>lineSlots(roster,ids).map(player=>player?`<button ${attribute}="${esc(player.id)}" title="Remove ${esc(player.name)}"><span>${esc(player.number||'—')}</span>${esc(player.name)} ×</button>`:'<span class="unknown-slot" aria-label="Unknown player">?</span>').join('');
 const renderSelected=()=>{$('#line-count').textContent=selected.length;$('#opponent-line-count').textContent=opponentSelected.length;$('#selected-line').innerHTML=slotMarkup(t.players,selected,'data-selected-player');$('#selected-opponent-line').innerHTML=slotMarkup(g.opponents,opponentSelected,'data-selected-opponent');$('#modal').querySelectorAll('[data-selected-player]').forEach(button=>button.onclick=()=>{selected=selected.filter(id=>id!==button.dataset.selectedPlayer);update();});$('#modal').querySelectorAll('[data-selected-opponent]').forEach(button=>button.onclick=()=>{opponentSelected=opponentSelected.filter(id=>id!==button.dataset.selectedOpponent);update();});};
 const update=()=>{$('#modal').querySelectorAll('[data-player]').forEach(button=>button.classList.toggle('selected',selected.includes(button.dataset.player)));$('#modal').querySelectorAll('[data-opponent-player]').forEach(button=>button.classList.toggle('selected',opponentSelected.includes(button.dataset.opponentPlayer)));renderSelected();};
 const renderPlayers=()=>{const players=playersForGroup(t,groupId),picker=$('#line-player-picker');picker.innerHTML=players.map(player=>`<button data-player="${esc(player.id)}"><span class="num">${esc(player.number||'—')}</span>${esc(player.name)}</button>`).join('');$('#group-empty').hidden=players.length>0;picker.querySelectorAll('[data-player]').forEach(button=>button.onclick=()=>{const id=button.dataset.player;if(selected.includes(id))selected=selected.filter(playerId=>playerId!==id);else if(selected.length<7)selected.push(id);else{toast('All seven positions are filled.');return;}update();});};
 renderPlayers();update();
 $('#modal').querySelectorAll('[data-opponent-player]').forEach(button=>button.onclick=()=>{const id=button.dataset.opponentPlayer;if(opponentSelected.includes(id))opponentSelected=opponentSelected.filter(playerId=>playerId!==id);else if(opponentSelected.length<7)opponentSelected.push(id);else{toast('All seven opponent positions are filled.');return;}update();});
 $('#modal').querySelectorAll('[data-line-group]').forEach(button=>button.onclick=()=>{groupId=button.dataset.lineGroup;$('#modal').querySelectorAll('[data-line-group]').forEach(item=>item.classList.toggle('selected',item===button));$('#manage-line-group').hidden=groupId==='all';renderPlayers();update();});
 $('#manage-line-group').onclick=()=>manageLineGroup(groupId,draftState());$('#new-line-group').onclick=()=>createLineGroup(draftState());
 $('#clear-line').onclick=()=>{selected=[];update();};$('#clear-opponent-line').onclick=()=>{opponentSelected=[];update();};
 $('#modal').querySelectorAll('[data-start]').forEach(button=>button.onclick=()=>{starting=button.dataset.start;$('#modal').querySelectorAll('[data-start]').forEach(item=>item.classList.toggle('selected',item===button));});
 $('#modal').querySelectorAll('[data-dir]').forEach(button=>button.onclick=()=>{direction=Number(button.dataset.dir);$('#modal').querySelectorAll('[data-dir]').forEach(item=>item.classList.toggle('selected',item===button));});
 $('#start-point').onclick=async()=>{g.events.push(event('point_start',{line:selected,opponentLine:opponentSelected,starting,direction}));closeModal();tab='track';await commit();};
}
function createLineGroup(draft){const t=team();let members=new Set(draft.selected);modal('Create a player group',`<form id="group-form"><p>Name the group, then choose any players who should appear when it is selected during line setup.</p><label class="field" for="group-name">Group name</label><input id="group-name" placeholder="e.g. O-line" maxlength="100" required autofocus><label class="field">Players</label><div class="player-picker group-builder">${t.players.map(player=>`<button type="button" data-group-player="${esc(player.id)}" class="${members.has(player.id)?'selected':''}"><span class="num">${esc(player.number||'—')}</span>${esc(player.name)}</button>`).join('')}</div><div class="modal-foot"><button type="button" id="back-to-line">Back to line</button><button type="submit" class="primary">Create group</button></div></form>`);
 $('#modal').querySelectorAll('[data-group-player]').forEach(button=>button.onclick=()=>{const id=button.dataset.groupPlayer;if(members.has(id))members.delete(id);else members.add(id);button.classList.toggle('selected',members.has(id));});
 $('#back-to-line').onclick=()=>selectLine(draft);
 $('#group-form').onsubmit=async e=>{e.preventDefault();const name=$('#group-name').value.trim();if(!name)return;if(!members.size){toast('Choose at least one player for the group.');return;}const group={id:uid(),name,playerIds:[...members]};t.groups.push(group);await persist();selectLine({...draft,groupId:group.id});toast(`${name} created.`);};
}
function manageLineGroup(groupId,draft){const t=team(),group=t.groups.find(group=>group.id===groupId);if(!group){selectLine({...draft,groupId:'all'});return;}let members=new Set(group.playerIds);modal(`Manage ${group.name}`,`<form id="manage-group-form"><p>Rename this group or change which players appear when it is selected.</p><label class="field" for="manage-group-name">Group name</label><input id="manage-group-name" value="${esc(group.name)}" maxlength="100" required autofocus><label class="field">Players</label><div class="player-picker group-builder">${t.players.map(player=>`<button type="button" data-group-player="${esc(player.id)}" class="${members.has(player.id)?'selected':''}"><span class="num">${esc(player.number||'—')}</span>${esc(player.name)}</button>`).join('')}</div><div class="modal-foot"><button type="button" class="danger" id="delete-line-group">Delete group</button><button type="button" id="cancel-group-edit">Back to line</button><button type="submit" class="primary">Save changes</button></div></form>`);
 $('#modal').querySelectorAll('[data-group-player]').forEach(button=>button.onclick=()=>{const id=button.dataset.groupPlayer;if(members.has(id))members.delete(id);else members.add(id);button.classList.toggle('selected',members.has(id));});
 $('#cancel-group-edit').onclick=()=>selectLine(draft);
 $('#manage-group-form').onsubmit=async e=>{e.preventDefault();const name=$('#manage-group-name').value.trim();if(!name)return;if(!members.size){toast('Choose at least one player for the group.');return;}group.name=name;group.playerIds=[...members];await persist();selectLine({...draft,groupId});toast(`${name} updated.`);};
 $('#delete-line-group').onclick=()=>{modal(`Delete ${group.name}?`,`<p>This removes the player group. It does not delete any players or change the seven currently selected for this point.</p><div class="modal-foot"><button id="keep-line-group">Keep group</button><button class="danger" id="confirm-delete-group">Delete group</button></div>`);$('#keep-line-group').onclick=()=>manageLineGroup(groupId,draft);$('#confirm-delete-group').onclick=async()=>{t.groups=t.groups.filter(item=>item.id!==groupId);await persist();selectLine({...draft,groupId:'all'});toast(`${group.name} deleted.`);};};
}
function opponentRoster(){const g=game();modal('Opponent players',`<form id="opponents-form"><p>Add known opponents using one player per line, with an optional number after a comma. You can always record an opponent as Unknown.</p>${g.opponents.length?`<p>${g.opponents.map(p=>esc(playerLabel(p))).join(' · ')}</p>`:''}<textarea id="opponents-input" placeholder="Taylor, 22&#10;Number 10, 10"></textarea><div class="modal-foot"><button type="button" data-cancel>Close</button><button type="submit" class="primary">Add players</button></div></form>`);$('#opponents-form').onsubmit=async e=>{e.preventDefault();g.opponents.push(...parsePlayers($('#opponents-input').value));closeModal();await commit();};}
function quickLineButtons(roster,ids,attribute,excludeId=null){return lineSlots(roster,ids).map((player,index)=>player?.id===excludeId?`<span class="quick-player current-holder"><span>${esc(player.number||'—')}</span>${esc(player.name)} · disc</span>`:`<button class="quick-player" ${attribute}="${esc(player?.id||'')}" data-slot="${index}"><span>${esc(player?.number||'?')}</span>${esc(player?.name||'Unknown')}</button>`).join('');}
function recordLocation(location){const g=game(),s=gameState(g),t=team(),ourIds=s.point.line||[],opponentIds=s.point.opponentLine||[],offenseRoster=s.side==='us'?t.players:g.opponents,offenseIds=s.side==='us'?ourIds:opponentIds,defenseRoster=s.side==='us'?g.opponents:t.players,defenseIds=s.side==='us'?opponentIds:ourIds;
 if(s.needsPickup){let defenderId=s.side==='them'?s.marker:null;modal('Who has the disc?',`<p>Tap the player taking possession. Unknown slots are shown as <strong>?</strong>.</p><div class="quick-heading">${esc(s.side==='us'?t.name:g.opponent)}</div><div class="quick-line">${quickLineButtons(offenseRoster,offenseIds,'data-quick-holder')}</div>${defenseIds.length?`<div class="quick-heading">Defender <span>optional</span></div><div class="quick-line secondary">${quickLineButtons(defenseRoster,defenseIds,'data-quick-defender')}</div>`:''}<div class="modal-foot"><button data-cancel>Cancel</button></div>`);$('#modal').querySelectorAll('[data-quick-defender]').forEach(button=>button.onclick=()=>{defenderId=button.dataset.quickDefender||null;$('#modal').querySelectorAll('[data-quick-defender]').forEach(item=>item.classList.toggle('selected',item===button));});$('#modal').querySelectorAll('[data-quick-holder]').forEach(button=>button.onclick=async()=>{g.events.push(event('possession_start',{side:s.side,playerId:button.dataset.quickHolder||null,location,markerId:s.side==='them'?defenderId:null,opponentMarkerId:s.side==='us'?defenderId:null}));closeModal();await commit();});return;}
 let outcome='complete',defenderId=null;const attacksRight=s.point.direction*(s.side==='us'?1:-1)===1,goalEnd=attacksRight?location.x>=g.field.length-g.field.endzone:location.x<=g.field.endzone;
 const record=async(receiverId,chosenOutcome=outcome)=>{const finalOutcome=chosenOutcome==='complete'&&goalEnd?'goal':chosenOutcome;g.events.push(event('pass',{side:s.side,throwerId:s.holder,receiverId:['throwaway','stall'].includes(finalOutcome)?null:receiverId||null,from:s.location,to:finalOutcome==='stall'?s.location:location,outcome:finalOutcome,markerId:s.side==='them'?s.marker:null,receiverDefenderId:s.side==='them'?defenderId:null,opponentReceiverDefenderId:s.side==='us'?defenderId:null,blockerId:finalOutcome==='block'&&s.side==='them'?defenderId:null}));closeModal();await commit();if(finalOutcome==='goal'){toast(`${s.side==='us'?'Your team':'Opponent'} scores. Choose the next line.`);selectLine();}};
 modal(goalEnd?'Select the scorer':'Select the receiver',`<p><strong>${esc(playerName(s.holder))}</strong> · ${Math.hypot(location.x-s.location.x,location.y-s.location.y).toFixed(1)} yd ${goalEnd?'into the end zone':''}</p><div class="quick-heading">${esc(s.side==='us'?t.name:g.opponent)} · receiver</div><div class="quick-line">${quickLineButtons(offenseRoster,offenseIds,'data-quick-receiver',s.holder)}</div>${defenseIds.length?`<div class="quick-heading">Receiver’s defender <span>optional · select before receiver</span></div><div class="quick-line secondary">${quickLineButtons(defenseRoster,defenseIds,'data-quick-defender')}</div>`:''}<div class="quick-outcomes"><button data-quick-outcome="complete" class="selected">${goalEnd?'★ Goal':'✓ Catch'}</button><button data-quick-outcome="drop">Drop</button><button data-quick-outcome="block">Block</button><button data-immediate-outcome="throwaway">Throwaway</button><button data-immediate-outcome="stall">Stall</button></div><div class="modal-foot"><span class="hint">Tap a receiver to record immediately.</span><button data-cancel>Cancel</button></div>`);
 $('#modal').querySelectorAll('[data-quick-defender]').forEach(button=>button.onclick=()=>{defenderId=button.dataset.quickDefender||null;$('#modal').querySelectorAll('[data-quick-defender]').forEach(item=>item.classList.toggle('selected',item===button));});
 $('#modal').querySelectorAll('[data-quick-outcome]').forEach(button=>button.onclick=()=>{outcome=button.dataset.quickOutcome;$('#modal').querySelectorAll('[data-quick-outcome]').forEach(item=>item.classList.toggle('selected',item===button));});
 $('#modal').querySelectorAll('[data-immediate-outcome]').forEach(button=>button.onclick=()=>record(null,button.dataset.immediateOutcome));
 $('#modal').querySelectorAll('[data-quick-receiver]').forEach(button=>button.onclick=()=>record(button.dataset.quickReceiver||null));
}
async function undo(){const g=game();if(!g?.events.length)return;g.revisions??=[];const removed=g.events.pop();g.revisions.push({at:new Date().toISOString(),action:'undo',event:removed});highlightedPassId=null;await commit();toast(`${removed.type.replaceAll('_',' ')} undone.`);}
function changeReceiver(id){const g=game(),index=g.events.findIndex(event=>event.id===id),pass=g.events[index],point=pointsOf(g).find(point=>point.events.some(event=>event.id===id));if(!pass||pass.type!=='pass'||!point)return;const roster=pass.side==='us'?team().players:g.opponents,playerIds=pass.side==='us'?point.line:point.opponentLine;modal('Change receiver',`<p>Select the correct receiver. If this player made the next throw, that thrower will be corrected too.</p><div class="quick-line">${quickLineButtons(roster,playerIds,'data-correct-receiver')}</div><div class="modal-foot"><button data-cancel>Cancel</button></div>`);$('#modal').querySelectorAll('[data-correct-receiver]').forEach(button=>button.onclick=async()=>{const oldReceiver=pass.receiverId,newReceiver=button.dataset.correctReceiver||null,next=g.events[index+1];g.revisions??=[];g.revisions.push({at:new Date().toISOString(),action:'change_receiver',event:structuredClone(pass),nextEvent:next?.type==='pass'?structuredClone(next):null});pass.receiverId=newReceiver;if(next?.type==='pass'&&next.side===pass.side&&next.throwerId===oldReceiver)next.throwerId=newReceiver;closeModal();await commit();toast('Receiver updated.');});}
function editPass(id){const g=game(),e=g.events.find(e=>e.id===id),p=pointsOf(g).find(p=>p.events.some(e=>e.id===id)),line=team().players.filter(x=>p.line.includes(x.id)),ps=e.side==='us'?team().players:g.opponents;modal('Correct pass details',`<form id="edit-form"><p>Correct players, defensive assignments, or coordinates. The recorded outcome stays ${esc(e.outcome)}. To change the outcome of a recent play, undo back to that play and record it again.</p><div class="form-grid"><div><label class="field" for="edit-thrower">Thrower</label><select id="edit-thrower">${options(ps,e.throwerId)}</select></div><div><label class="field" for="edit-receiver">Receiver / target</label><select id="edit-receiver">${options(ps,e.receiverId)}</select></div></div><div class="form-grid">${[['from-x','Start X',e.from.x,g.field.length],['from-y','Start Y',e.from.y,g.field.width],['to-x','End X',e.to.x,g.field.length],['to-y','End Y',e.to.y,g.field.width]].map(([id,label,val,max])=>`<div><label class="field" for="${id}">${label} (yd)</label><input type="number" step="any" min="0" max="${max}" id="${id}" value="${val}" required></div>`).join('')}</div>${e.side==='them'?`<div class="form-grid"><div><label class="field" for="edit-marker">Marker</label><select id="edit-marker">${options(line,e.markerId)}</select></div><div><label class="field" for="edit-defender">Receiver’s defender</label><select id="edit-defender">${options(line,e.receiverDefenderId)}</select></div></div><label class="field" for="edit-blocker">Block credited to</label><select id="edit-blocker">${options(line,e.blockerId)}</select>`:''}<p>Edits apply to this pass only. Check adjacent plays if the disc holder or location changed.</p><div class="modal-foot"><button type="button" data-cancel>Cancel</button><button type="submit" class="primary">Save correction</button></div></form>`);$('#edit-form').onsubmit=async ev=>{ev.preventDefault();g.revisions??=[];g.revisions.push({at:new Date().toISOString(),action:'edit',event:structuredClone(e)});e.throwerId=$('#edit-thrower').value||null;e.receiverId=$('#edit-receiver').value||null;e.from={x:Number($('#from-x').value),y:Number($('#from-y').value)};e.to={x:Number($('#to-x').value),y:Number($('#to-y').value)};if(e.side==='them'){e.markerId=$('#edit-marker').value||null;e.receiverDefenderId=$('#edit-defender').value||null;e.blockerId=$('#edit-blocker').value||null;}closeModal();await commit();};}
function download(content,label){const blob=new Blob([JSON.stringify({...content,exportedAt:new Date().toISOString()},null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`fieldbook-${label}-${new Date().toISOString().slice(0,10)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),30000);toast('JSON export created.');}
function exportGame(){const g=game();download({...emptyData(),teams:[team()],games:[g],sources:data.sources.filter(s=>s.id===g.source?.id)},'game');}
async function importFile(file){if(!file)return;if(file.size>50000000){toast('Choose a file smaller than 50 MB.');return;}try{toast('Reading your game file…');const buf=await file.arrayBuffer(),sig=new Uint8Array(buf);let incoming;if(sig[0]===80&&sig[1]===75)incoming=convertStatto(await readStattoZip(buf));else{const raw=JSON.parse(new TextDecoder().decode(buf));incoming=raw.format==='fieldbook'?validateData(raw):convertStatto(raw);}const result=mergeData(data,incoming);modal('Ready to import',`<p><strong>${incoming.teams.length} teams</strong> · <strong>${result.added} new games</strong> · ${result.skipped} existing games will be kept.</p>${incoming.sources.length?'<div class="notice">Statto source records are preserved. Historical field coordinates are interpreted as normalized portrait coordinates on a 110 × 40 yd field; original pitch types are retained. Defender yardage is unavailable for historical games.</div>':''}<p>This merges into your library on this device. Your existing games will not be overwritten.</p><div class="modal-foot"><button data-cancel>Cancel</button><button class="primary" id="confirm-import">Import games</button></div>`);$('#confirm-import').onclick=async()=>{data=result.data;view='games';gameId=null;teamId=incoming.teams[0]?.id||null;closeModal();await commit();toast(`Imported ${result.added} games. ${result.skipped} existing games kept.`);};}catch(e){toast('Import failed: '+e.message);}}
function finish(){const g=game();g.finished=true;commit();}
function deleteGame(){const g=game();modal('Delete this game?',`<p>This permanently removes ${esc(team()?.name||'your team')} vs ${esc(g.opponent)} and its play-by-play from this device. Export it first if you may need it later.</p><div class="modal-foot"><button data-cancel>Keep game</button><button class="danger" id="confirm-delete-game">Delete game</button></div>`);$('#confirm-delete-game').onclick=async()=>{data.games=data.games.filter(item=>item.id!==g.id);gameId=null;view='games';closeModal();await persist();render();toast('Game deleted.');};}
function help(){modal('A field guide',`<ol class="help-list"><li>Create a team and add at least seven players.</li><li>Start a game and choose the line, starting O/D, and attacking direction.</li><li>Tap the disc’s initial location and select the holder.</li><li>Tap each throw’s destination, choose its target and outcome. A completed pass keeps possession; a turnover prompts a new pickup.</li><li>On defense, optionally select the marker and receiver’s defender. The latter becomes the next marker.</li><li>After a goal, select the next line. O/D and direction default from the previous point.</li></ol><h3>Stat definitions</h3><p>Possessions initiated credit the first player controlling the disc after a pull or turnover. Goals credit the scorer, assists credit the final thrower, and secondary assists credit the thrower of the preceding completed pass in that possession.</p><p>Distance is straight-line distance between throw and catch. Gain is signed forward progress. Only completed throws count toward yardage. An offensive opportunity counts once for every player on the starting line if the team starts on O or the opponent turns over.</p><p>A drop credits a drop to the intended receiver; throwaways and blocked throws count as thrower turnovers. On opponent throws, the marker is charged throwing yardage/assists allowed, the receiver defender is charged receiving yardage/goals allowed and target attempts. A throwaway credits the marker with a forced throwaway.</p><p>Unknown or unassigned defenders receive no individual credit. This MVP uses starting lines; mid-point substitutions are not recorded.</p><div class="modal-foot"><button data-cancel class="primary">Got it</button></div>`);}
const actions={'new-team':newTeam,'new-game':newGame,'select-games':selectGames,'show-heatmap':showHeatmap,'huck-chart':huckChart,point:selectLine,opponents:opponentRoster,undo,finish,'delete-game':deleteGame,resume:()=>{game().finished=false;commit();},import:()=>$('#import-file').click(),export:()=>download(data,'library'),'export-game':exportGame,help};
$('#import-file').onchange=e=>{importFile(e.target.files[0]);e.target.value='';};
try{data=await readStore()||emptyData();validateData(data);}catch(e){saveLabel='Storage unavailable';toast('Could not read local storage. Import a JSON backup if needed.');}
if(!data.teams.length){try{const r=await fetch('./initial-data.json');if(r.ok){data=validateData(await r.json());await persist();}}catch{}}
render();
if('serviceWorker' in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});
